# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-13 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180112_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('\u7537', '\u7537'), ('\u5973', '\u5973')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='belong_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
