# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-13 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180113_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
