# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-14 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180113_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='upload/profile_image'),
        ),
    ]
